# Standards: 0.11
---
branches:
  only:
    - master
    - build
    
group: stable
dist: amazonlinux

language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

env:
  - ANSIBLE_INSTALL_VERSION=2.2.3
  - ANSIBLE_INSTALL_VERSION=2.3.3
  - ANSIBLE_INSTALL_VERSION=2.4.5
  - ANSIBLE_INSTALL_VERSION=2.5.5
  - ANSIBLE_INSTALL_VERSION=2.6.0

# Make sure we have the latest package list
before_install:
  - sudo apt-get update
  
install:
  # Install ansible
  - pip install ansible ansible-review

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - make syntax
  - make review

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
